name: WinRAR Keygen

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'keygen/*.json'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate key 
      shell: powershell
      run: bin/x64-Release/winrar-keygen.exe "${{secrets.TEXT1}}" "${{secrets.TEXT2}}" | out-file -encoding ascii rarreg.key
      
    - name: Upload key
      uses: actions/upload-artifact@v2
      with:
        name: rarreg_file
        path: rarreg.key
        retention-days: 90
